
GET http://localhost:9002/editorial/listar HTTP/1.1
###

GET http://localhost:9002/editorial/ver/1 HTTP/1.1

###

POST http://localhost:9002/editorial/crear HTTP/1.1
content-type: application/json

{
    "name": "PRUEBA EDITORIAL CREAR",
    "countryId":1,
    "createdUser": "FC"
}

###

PUT http://localhost:9002/editorial/editar/2 HTTP/1.1
content-type: application/json

{
    "name": "PRUEBA EDITORIAL EDITAR",
    "countryId":2,
    "createdUser": "KC"
}

###

DELETE http://localhost:9002/editorial/borrar/2 HTTP/1.1