
GET http://localhost:9002/document/listar HTTP/1.1

###

GET http://localhost:9002/document/author HTTP/1.1

###

GET http://localhost:9002/document/ver/1 HTTP/1.1

###

GET http://localhost:9002/document/category/1 HTTP/1.1

###

GET http://localhost:9002/document/busqueda/felicidad HTTP/1.1

###

POST http://localhost:9002/document/crear HTTP/1.1
content-type: application/json

{
    "title": "PRUEBA DOCUMENTO CREAR 2",
    "description": "PRUEBA DOCUMENTO CREAR 2",
    "imagenPath": "IMAGEN PATH 2",
    "pdfPath": "PDF PATH 2",
    "userId": 1,
    "categoryId": 1,
    "authorId": 1,
    "editorialId": 1,
    "lenguajeId": 1,
    "publicationDate": "2019-10-12",
    "createdUser": "FC"
}

###

PUT http://localhost:9002/document/editar/2 HTTP/1.1
content-type: application/json

{
    "title": "PRUEBA DOCUMENTO EDITAR 2",
    "description": "PRUEBA DOCUMENTO EDITAR 2",
    "imagenPath": "IMAGEN PATH 2",
    "pdfPath": "PDF PATH 2",
    "userId": 1,
    "categoryId": 1,
    "authorId": 1,
    "editorialId": 1,
    "lenguajeId": 1,
    "publicationDate": "2019-10-12",
    "createdUser": "KM"
}

###

DELETE http://localhost:9002/document/borrar/2 HTTP/1.1