
GET http://localhost:9002/country/listar HTTP/1.1
###

GET http://localhost:9002/country/ver/1 HTTP/1.1

###

POST http://localhost:9002/country/crear HTTP/1.1
content-type: application/json

{
    "name": "GUATEMALA",
    "createdUser": "FC"
}

###

PUT http://localhost:9002/country/editar/2 HTTP/1.1
content-type: application/json

{
    "name": "HONDURAS",
    "createdUser": "KC"
}

###

DELETE http://localhost:9002/country/borrar/2 HTTP/1.1