
GET http://localhost:9002/systemUser/listar HTTP/1.1
###

GET http://localhost:9002/systemUser/ver/1 HTTP/1.1

###

POST http://localhost:9002/systemUser/crear HTTP/1.1
content-type: application/json

{
    "name": "USER CREADO",
    "password": "123456783",
    "email": "FC3@GMAIL.COM",
    "telephone": "098765433",
    "createdUser": "FC"
}

###

PUT http://localhost:9002/systemUser/editar/2 HTTP/1.1
content-type: application/json

{
    "name": "USER EDITADO 2",
    "password": "1234567822",
    "email": "FC22@GMAIL.COM",
    "telephone": "0987654322",
    "createdUser": "KC"
}

###

DELETE http://localhost:9002/systemUser/borrar/2 HTTP/1.1