SET DEFINE OFF

INSERT INTO SYSTEM_PERMISSIONS (PERMISSIONS_ID, NAME, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER) 
VALUES (1.0, 'Dowmload', 1.0, to_timestamp('30/08/2019 02:55', 'YYYY-MM-DD HH24:MI:SS'), 'MADX', to_timestamp('30/08/2019 02:55', 'YYYY-MM-DD HH24:MI:SS'), 'NULL');

INSERT INTO SYSTEM_PERMISSIONS (PERMISSIONS_ID, NAME, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER) 
VALUES (2.0, 'Reading', 1.0, to_timestamp('30/08/2019 02:53', 'YYYY-MM-DD HH24:MI:SS'), 'MADX', to_timestamp('30/08/2019 02:53', 'YYYY-MM-DD HH24:MI:SS'), 'NULL');

INSERT INTO SYSTEM_PERMISSIONS (PERMISSIONS_ID, NAME, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER) 
VALUES (3.0, 'Write', 1.0, to_timestamp('30/08/2019 02:54', 'YYYY-MM-DD HH24:MI:SS'), 'MADX', to_timestamp('30/08/2019 02:54', 'YYYY-MM-DD HH24:MI:SS'), 'NULL');

-- Importar Datos a la Tabla SYSTEM_PERMISSIONS del Archivo C:\Users\Ervin LG\UMG20192\DesarrolloWeb\Data_proyect\SystemPermissions.csv . Tarea correcta enviada a hoja de trabajo.
