SET DEFINE OFF

INSERT INTO SYSTEM_ROLES_PERMISSIONS (SYSTEM_ROLE_PERMISSION_ID, ROL_ID, PERMISSIONS_ID, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, FK_SYSTEM_PERMISSION, FK_SYSTEM_ROL) 
VALUES (1.0, '1', 'DOW', 1.0, to_timestamp('30/08/2019 03:02', 'YYYY-MM-DD HH24:MI:SS'), 'MADX', to_timestamp('30/08/2019 03:02', 'YYYY-MM-DD HH24:MI:SS'), 'NULL', 1.0, 1.0);

INSERT INTO SYSTEM_ROLES_PERMISSIONS (SYSTEM_ROLE_PERMISSION_ID, ROL_ID, PERMISSIONS_ID, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, FK_SYSTEM_PERMISSION, FK_SYSTEM_ROL) 
VALUES (2.0, '1', 'READ', 1.0, to_timestamp('30/08/2019 03:03', 'YYYY-MM-DD HH24:MI:SS'), 'MADX', to_timestamp('30/08/2019 03:03', 'YYYY-MM-DD HH24:MI:SS'), 'NULL', 1.0, 1.0);

INSERT INTO SYSTEM_ROLES_PERMISSIONS (SYSTEM_ROLE_PERMISSION_ID, ROL_ID, PERMISSIONS_ID, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, FK_SYSTEM_PERMISSION, FK_SYSTEM_ROL) 
VALUES (3.0, '1', 'WRIT', 1.0, to_timestamp('30/08/2019 03:03', 'YYYY-MM-DD HH24:MI:SS'), 'MADX', to_timestamp('30/08/2019 03:03', 'YYYY-MM-DD HH24:MI:SS'), 'NULL', 1.0, 1.0);

-- Importar Datos a la Tabla SYSTEM_ROLES_PERMISSIONS del Archivo C:\Users\Ervin LG\UMG20192\DesarrolloWeb\Data_proyect\SystemRolePermission.csv . Tarea correcta enviada a hoja de trabajo.
