SET DEFINE OFF

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (1.0, 'branding conrporativo', 'Sabemos que la dirección y gestión de toda actividad empresarial exige una responsabilidad de primera magnitud por parte del directivo. Es por esto que la Estrategia y el Management forman parte del core de nuestra Business School Universidad Mayor', 'images/BrandingCorporativo.png', 'Documents/BrandingCorporativo.pdf', 0.0, 1.0, 1.0, 1.0, 1.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 1.0, 1.0, 1.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (2.0, 'ANALISIS DE SISTEMAS LINEALES', 'abstracta un fen´omeno en base al objetivo que el observador/ingeniero requiera en cada caso particular. En este texto abordamos el an´alisis de un tipo particular de sistemas, aquellos conocidos como sistemas lineales. Esta propiedad, si', 'images/Análisis de sistemas lineales.png', 'Documents/Análisis de sistemas lineales.pdf', 0.0, 1.0, 4.0, 17.0, 1.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 17.0, 4.0, 1.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (3.0, 'bioquimica ilustrada', ' a otras fuentes de datos, por ejemplo, y de manera particular, habrá que consultar la hoja informativa que se adjunta con cada medicamento, para tener certeza de que la información de esta obra es precisa y no se han introducido cambios ', 'images/bioquímica ilustrada.png', 'Documents/bioquímica ilustrada.pdf', 0.0, 1.0, 2.0, 2.0, 2.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 2.0, 2.0, 2.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (4.0, 'El príncipe ', 'nos dignos de su grandeza. Deseando, pues, presentarme ante Vuestra Magnificencia con alglún testimonio de mi sometimiento, no he encontrado entre lo poco que poseo nada que me sea más caro o que tanto estime como el conocimiento .', 'images/El principe MAQUIAVELO.png', 'Documents/El principe MAQUIAVELO.pdf', 0.0, 1.0, 3.0, 3.0, 3.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 3.0, 3.0, 3.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (5.0, 'Las pasiones ordinarias', 'bres se apoderan de los signos para vivir y dejar ver sus emociones. Sin sentirlas, las traduce ante un público que las comprende, al mismo tiempo que conoce el artificio del espectáculo. ¿Cuál es el estatus del cuerpo en la comunicación? ¿', 'images/Las pasiones ordinarias.png', 'Documents/Las pasiones ordinarias.pdf', 0.0, 1.0, 5.0, 19.0, 5.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 19.0, 5.0, 5.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (6.0, 'Los Siete Sermones a los muertos', 'rior y por ello no se cuestionan ya su propia existencia como egos generadores de deseos. Así al no seguir avanzando por el sendero que conduce a la iluminación  se han convertido en "muertos vivientes". Stephan Hoeller muestra la vida y ', 'images/Los 7 sermones a los muertos.png', 'Documents/Los 7 sermones a los muertos.pdf', 0.0, 1.0, 6.0, 21.0, 6.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 21.0, 6.0, 6.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (7.0, 'Manual Practico de Instalaciones Electricas', 'El autor nos ofrece esta primer edición, la cual ha actualizado considerando los cambios que han habido en las normas técnicas para instalaciones eléctricas, incorporando conceptos adicionales y un buen número de ilustraciones para ', 'images/Manual Practico de Instalaciones Electricas.png', 'Documents/Manual Practico de Instalaciones Electricas.pdf', 0.0, 1.0, 7.0, 24.0, 7.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 24.0, 7.0, 7.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (8.0, 'control de calidad', 'La dirección de la calidad es un viaje hacia la mejora continua. En nuestro trabajo pretendemos dar una guía para recorrer este camino, así como identificar el rol y responsabilidades en el liderazgo de los esfuerzos de mejora en la organi', 'images/Control de Calidad.png', 'Documents/Control de Calidad.pdf', 0.0, 1.0, 4.0, 10.0, 8.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 10.0, 4.0, 8.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (9.0, 'como programar en java', 'as ediciones, este libro ha demostrado ser un excelente texto para cursos universitarios y profesionales que otros y yo hemos desarrollado para enseñar el lenguaje de programación Java. Una de las cualidades que hacen de este libro un e', 'images/Como programar en Java.png', 'Documents/Como programar en Java.pdf', 0.0, 1.0, 4.0, 11.0, 8.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 11.0, 4.0, 8.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (10.0, 'como programar en c y java', 'Instrucciones y funciones de control en CArreglos, apuntadores y estructuras de datos ligadas en CProcesamiento de caracteres y cadenas en CEstructuras, uniones y manipulación de bits en CEntrada/salida con formato y archivos en ', 'images/Como Programar en C y Java.png', 'Documents/Como Programar en C y Java.pdf', 0.0, 1.0, 4.0, 12.0, 8.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 12.0, 4.0, 8.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (11.0, 'C�?LCULO UNA VARIABLE ', 's de difícil comprensión. De acuerdo con el autor, George Thomas, “hemos intentado escribir el libro con tanta claridad y precisión como ha sido posible�?. Además, hemos restablecido los contenidos para que sean más lógicos y ', 'images/Calculo. Una Variable.png', 'Documents/Calculo. Una Variable.pdf', 0.0, 1.0, 4.0, 13.0, 8.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 13.0, 4.0, 8.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (12.0, 'Aritmetica y algebra', 'El colegio nacional de matematicas es una institutcion que desde su fundacion , ah impartido cursos de regularizacion en las areas matematicas, fisica y quimica', 'images/Aritmetica y Algebra.png', 'Documents/Aritmetica y Algebra.pdf', 0.0, 1.0, 8.0, 26.0, 8.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 26.0, 8.0, 8.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (13.0, 'El hombre y sus simbolos', 'je directo, personal y significativo que utiliza símbolos comunes a toda la humanidad de una forma totalmente individualizada, que, a su vez, solo puede interpretarse mediante una “clave�?, también individual.Texto-resumen ', 'images/El hombre y sus simbolos.png', 'Documents/El hombre y sus simbolos.pdf', 0.0, 1.0, 10.0, 28.0, 10.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 28.0, 10.0, 10.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (14.0, 'lenguaje, poder e identidad', 'uesta teórica de considerar el género y la identidad en términos de performance y performatividad ha constituido uno de los mayores impulsos teóricos en el feminismo y el los estudios gays y lesbianos en la década de los noventa. ', 'images/Butler Lenguaje Poder e Identidad OCR.png', 'Documents/Butler Lenguaje Poder e Identidad OCR.pdf', 0.0, 1.0, 11.0, 29.0, 11.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 29.0, 11.0, 11.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (15.0, 'C# GU�?A TOTAL DEL PROGRAMADOR', 'ntenido actualizado por completo a la versión 4.0 de C#, incluido en Visual Studio 2010. La obra fue escrita y mejorada por su autor Nicolás Arrioja Landa Cosio, quien es un investigador universitario, experto en C# y autor de cuatro lib', 'images/C Guia Total del Programador.png', 'Documents/C# Guia Total del Programador.pdf', 0.0, 1.0, 4.0, 4.0, 12.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 4.0, 4.0, 12.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (16.0, 'CURSO DE LINUX PARA NOVATOS, BRUTOS Y EXTREMADAMENTE TORPES', 'se sentirá usted, pero yo me sentiré feliz porque todavía no está terminada . Para un correcto aprovechamiento del curso se recomienda una lectura secuencial de cada uno de los capítulos en orden establecido en este indice. ', 'images/Curso de Linux para novatos, brutos y extremadamente torpes.png', 'Documents/Curso de Linux para novatos, brutos y extremadamente torpes.pdf', 0.0, 1.0, 4.0, 5.0, 13.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 5.0, 4.0, 13.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (17.0, 'con el diablo en el cuerpo', ' mil imprudencias, hasta que Marthe se da cuenta de que está embarazada. Todo va a cambiar con el final de la guerra, los cuatro años de grandes vacaciones" de la joven pareja. "El diablo en el cuerpo" es un clásico de la literatura fran', 'images/Con el diablo en el cuerpo.png', 'Documents/Con el diablo en el cuerpo.pdf', 0.0, 1.0, 6.0, 20.0, 17.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 20.0, 6.0, 17.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (18.0, 'Guia de html 5', 'os, sonido...) La descripción se basa en especificar en el texto la estructura lógica del contenido (títulos, párrafos de texto normal, enumeraciones, definiciones, citas, etc) así como los diferentes efectos que se quieren dar (espe', 'images/Curso-HTML5-v1.png', 'Documents/Curso-HTML5-v1.pdf', 0.0, 1.0, 4.0, 9.0, 19.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 9.0, 4.0, 19.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (19.0, 'cracking sin secretos', 'Para la mayoria el termino cracking contiene maticesrelacionadas con lo prohibido y desconocido ademas de extranio pero gracias a este curso logramos definirlo para la defensa ante todaws las ', 'images/Cracking-sin-secretos.png', 'Documents/Cracking-sin-secretos.pdf', 0.0, 1.0, 4.0, 14.0, 21.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 14.0, 4.0, 21.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (20.0, 'PL/SQL Básico', 'PL/SQL Es un lenguaje de programación interpretado. Éste lenguaje permite la creación de scripts, instrucciones que son posteriormente interpretados por el motor PL/SQL de Oracle. En éste pequeño libro veremos el paso .', 'images/Curso Oracle PLSQL 2.png', 'Documents/Curso Oracle PLSQL 2.pdf', 0.0, 1.0, 4.0, 7.0, 22.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 7.0, 4.0, 22.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (21.0, 'CURSO DE SEGURIDAD INFORM�?TICA Y CRIPTOGRAF�?A ', 'o de los métodos utilizados hasta mediados del siglo XX (criptografía clásica) permite aprender de forma simplificada los fundamentos de los métodos criptográficos actuales. A continuación se abordan en detalle los mecanismos ', 'images/Curso de seguridad informática y criptografía.png', 'Documents/Curso de seguridad informática y criptografía.pdf', 0.0, 1.0, 4.0, 8.0, 23.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 8.0, 4.0, 23.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (22.0, 'circuitos electricos ', 'l funcionamiento tanto de circuitos de corriente continua como de corriente alterna. La presentación entrelaza la teoría con ejemplos ilustrativos, lo que facilita la comprensión de la materia. Cada capítulo incluye una colección d', 'images/Circuitos Eléctricos.png', 'Documents/Circuitos Eléctricos.pdf', 0.0, 1.0, 4.0, 15.0, 24.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 15.0, 4.0, 24.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (23.0, 'Circuitos y dispositivos electronicos ', 'Por más de 40 años el libro de Robert L. Boylestad, Electrónica: Teoría de circuitos y dispositivos electrónicos ha sido el texto de referencia para estudiantes y profesionales en el campo de los dispositivos electrónicos y las aplicaciones ', 'images/Circuitos y Dispositivos Electronicos.png', 'Documents/Circuitos y Dispositivos Electronicos.pdf', 0.0, 1.0, 4.0, 6.0, 25.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 6.0, 4.0, 25.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (24.0, 'conocimiento y libertad', 'homenaje a Bertrand Russell, cuyo contenido, reproducido en este libro, ofrece no sólo los puntos de vista del autor sobre el filósofo, sino además una lúcida introducción a los aspectos lingüísticos y políticos del pensamiento de Chomsk', 'images/chomsky conocimiento y libertad.png', 'Documents/chomsky conocimiento y libertad.pdf', 0.0, 1.0, 6.0, 22.0, 26.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 22.0, 6.0, 26.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (25.0, 'abc de la mecatronica', 'Aunquenoesunconceptonuevo,estetérminohaadquiridounagranimportanciaenlosúltimosañosporelimpactodesusaplicaciones.Porlotanto,Mecatrónicanoesunapalabrasimplededefiniryaqueserefierealaautomatizacióndeprocesosb', 'images/ABC de la Mecatrónica.png', 'Documents/ABC de la Mecatrónica.pdf', 0.0, 1.0, 7.0, 25.0, 27.0, to_timestamp('29/08/2017 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', to_timestamp('29/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ervin', 2.0, 25.0, 7.0, 27.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (26.0, 'Analisis de Circuitos en Ingenieria', 'se pretende que la lectura de este libro sea una experiencia placentera aun cuando el texto sea por necesidad cientificamente rifuroso y un tanto matematico', 'images/Analisis de Circuitos en Ingenieria.png', 'Documents/Analisis de Circuitos en Ingenieria.pdf', 0.0, 1.0, 4.0, 14.0, 21.0, to_timestamp('17/06/2015 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('30/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Paco', to_timestamp('30/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Paco', 2.0, 14.0, 4.0, 21.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (27.0, 'Planificación estartegica', 'Cada vez más, se está reconociendo la importancia que tiene la Imagen Corporativa para el logro de los objetivos de cualquier organización, sea ésta privada o pública. Se pueden encontrar a muchos directivos diciendo “nuestra ', 'images/Planificación estartegica.png', 'Documents/Planificación estartegica.pdf', 0.0, 1.0, 1.0, 1.0, 21.0, to_timestamp('16/08/2016 00:00', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('30/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Daniel', to_timestamp('30/08/2019 00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Daniel', 2.0, 1.0, 1.0, 21.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (28.0, 'King, Stephen - IT (Eso)', 'It es una novela de terror publicada en 1986 por el escritor estadounidense Stephen King. Cuenta la historia de un grupo de siete niños que son aterrorizados por un malvado monstruo -al que llaman «Eso»- que es capaz de cambiar.', 'images/King, Stephen - IT (Eso).jpg', 'Documents/King, Stephen - IT (Eso).pdf', 0.0, 1.0, 12.0, 30.0, 32.0, to_timestamp('31/08/2019 05:03', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('31/08/2019 05:03', 'YYYY-MM-DD HH24:MI:SS'), 'NULL', to_timestamp('31/08/2019 05:03', 'YYYY-MM-DD HH24:MI:SS'), 'NULL', 2.0, 31.0, 12.0, 32.0, 2.0, 1.0);

INSERT INTO DOCUMENT (DOCUMENT_ID, TITLE, DESCRIPTION, IMAGEN_PATH, PDF_PATH, PRIVATED, USER_ID, CATEGORY_ID, AUTHOR_ID, EDITORIAL_ID, PUBLICATION_DATE, STATE, CREATED_ON, CREATED_USER, MODIFIED_ON, MODIFIED_USER, LENGUAJE_ID, FK_AUTOR, FK_CATEGORY, FK_EDITORIAL, FK_LENGUAJE, FK_SYSTEM_USER) 
VALUES (29.0, 'La Torre Oscura I: el pistolero', 'El pistolero es una novela del autor estadounidense Stephen King, y es el primer volumen de la serie de La Torre Oscura, que King considera como su magnum opus. Inicialmente una novela que juntaba cinco historias cortas publicadas ', 'images/Stephen King - La torre oscura I.jpg', 'Documents/Stephen King - La torre oscura I.pdf', 0.0, 1.0, 12.0, 30.0, 32.0, to_timestamp('31/08/2019 05:04', 'YYYY-MM-DD HH24:MI:SS'), 1.0, to_timestamp('31/08/2019 05:04', 'YYYY-MM-DD HH24:MI:SS'), 'NULL', to_timestamp('31/08/2019 05:04', 'YYYY-MM-DD HH24:MI:SS'), 'NULL', 2.0, 31.0, 12.0, 32.0, 2.0, 1.0);

-- Importar Datos a la Tabla DOCUMENT del Archivo C:\Users\Ervin LG\UMG20192\DesarrolloWeb\Data_proyect\document.csv . Tarea correcta enviada a hoja de trabajo.
